# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.14.22
loom_version=1.4-SNAPSHOT

# Mod Properties
mod_version=1.0.7
maven_group=com.shine
archives_base_name=shine-fabric-1.20.1

# Dependencies
fabric_version=0.92.2+1.20.1
modmenu_version=7.2.2
yacl_version=3.6.6+1.20.1-fabric
